version: 2

sources:
  - name: dbt_ts_assignment
    database: ae-ts-assignment
    schema: dbt_ts_assignment

    #loaded_at_field: does not apply for the provided data

    tables:
      - name: seed_autoqa_ratings_test
        description: Input data provided for autoqa ratings
      - name: seed_autoqa_reviews_test
        description: Input data provided for autoqa reviews
      - name: seed_autoqa_root_cause_test
        description: Input data provided for autoqa root causes
      - name: seed_manual_rating_test
        description: Input data provided for manual ratings
      - name: seed_manual_reviews_test
        description: Input data provided for manual reviews
      - name: seed_conversations_test
        description: Input data provided for conversations

models:
  - name: raw_autoqa_reviews
    description: >
      Raw data regarding automatically performed reviews.
      The grain of the model is autoqa_review_id,each review_id should be unique.
    meta:
      owner: "@thomas"
    columns:
      - name: autoqa_review_id
        description: Unique identifier for the review.
        tests:
          - not_null
          - unique
      - name: review_created_at_utc
        description: UTC timestamp of when the review was created.
      - name: review_updated_at_utc
        description: UTC timestamp of when the review was updated.

  - name: raw_autoqa_ratings
    description: >
      Raw ratings data regarding automatically performed reviews.
      The grain of the model is autoqa_rating_id, each rating should be unique.
    meta:
      owner: "@thomas"
    columns:
      - name: autoqa_rating_id
        description: Unique identifier for the rating.
        tests:
          - not_null
          - unique 
      - name: autoqa_review_id
        description: Unique identifier for the review that the respective rating corresponds to.
        tests:
          - not_null
      - name: external_ticket_id
        description: Unique identified for the external ticket that respective rating corresponds to.
        tests:
          - not_null

  - name: raw_autoqa_root_cause
    description: >
      Root causes for the rating that was submitted for a category in a review.
      Root causes are reasons that justify why the category was scored that way.
      For example, if there is a negative score in grammar then the root cause can be spelling mistakes and/or syntax errors.
    meta:
      owner: "@thomas"
    columns:
      - name: autoqa_rating_id
        description: Unique identifier for the rating
        tests:
          - not_null 
      - name: root_cause
        description: Reason provided to justify the submitted score for the corresponding category.
        tests:
          - not_null
      